#!/bin/bash

if [ $WM_PROJECT == "foam" ]; then
    # FOAM-Extend - OF_FLAVOUR=1
    export OF_VERSION=`echo $WM_PROJECT_VERSION | sed -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -2 | tr -d '\n'`
    export OF_FLAVOUR=1
else
    if [[ $WM_PROJECT_VERSION == *"v"* ]] && [ $WM_PROJECT_VERSION != "dev" ]
    then
        # OpenFOAM + (.com) - OF_FLAVOUR=2
        export OF_VERSION=`echo $WM_PROJECT_VERSION"-0" | sed -e 's/v//' -e 's/+//' -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -3 | tr -d '\n' | head -c4`
        export OF_FLAVOUR=2
    else
        # OpenFOAM (.org) - OF_FLAVOUR=3
        OF_VERSION=`echo $WM_PROJECT_VERSION"-00" | sed -e 's/v//' -e 's/+//' -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -1`
        if [ $OF_VERSION -lt 10 ]; then
            export OF_VERSION=`echo $WM_PROJECT_VERSION"-00" | sed -e 's/v//' -e 's/+//' -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -3 | tr -d '\n' | head -c3`
        else
            export OF_VERSION=`echo $WM_PROJECT_VERSION"-00" | sed -e 's/v//' -e 's/+//' -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -3 | tr -d '\n' | head -c4`
        fi
        export OF_FLAVOUR=3
        if [ $WM_PROJECT_VERSION == "dev" ]; then
            export OF_VERSION=9999
        fi
    fi
fi

wclean > /dev/null

wmake libso

if (( $? )) ; then 
    echo "\n\nOlaFlow project wave generation boundary conditions compilation failed"
    exit; else
    echo -e "\n\nOlaFlow project wave generation boundary conditions compiled successfully for $WM_PROJECT $WM_PROJECT_VERSION\n\n\n";  
fi

wclean > /dev/null
rm -f ../common/waveFun.dep

if [ $WM_PROJECT == "foam" ]; then
    rm -fr lnInclude
fi
