#!/bin/bash

wclean > /dev/null
wclean ihDyMFoam > /dev/null

wmake

if (( $? )) ; then 
    echo "ihFoam compilation failed"
    exit; else
    echo -e "\n\nihFoam compiled successfully for OpenFOAM 2.3.0\n\
        Note that this solver is really the regular interFoam.\n\
        Please read the README file for more details.\n\n\n";  
fi

wmake ihDyMFoam

if (( $? )) ; then 
    echo "ihDyMFoam compilation failed"
    exit; else
    echo -e "\n\nihDyMFoam compiled successfully for OpenFOAM 2.3.0\n\
        Note that this solver is really the regular interDyMFoam.\n\
        Please read the README file for more details.\n\n\n";   
fi

wclean > /dev/null
wclean ihDyMFoam > /dev/null
