#!/bin/bash

wclean > /dev/null
wclean ihDyMFoam > /dev/null

wmake

if (( $? )) ; then 
    echo "ihFoam compilation failed"
    exit; else
    echo -e "\n\nihFoam compiled successfully for OpenFOAM 2.3.0\n\n\n";
fi

wmake ihDyMFoam

if (( $? )) ; then 
    echo "ihDyMFoam compilation failed"
    exit; else
    echo -e "\n\nihDyMFoam compiled successfully for OpenFOAM 2.3.0\n\n\n";   
fi

wclean > /dev/null
wclean ihDyMFoam > /dev/null
