#!/bin/bash

mkdir 0

echo blockMesh meshing...
blockMesh > blockMesh.log

echo Preparing 0 folder...
rm -fr 0
cp -r 0.org 0
rm 0/pointDisplacement_piston
mv 0/pointDisplacement_flap 0/pointDisplacement

echo Setting the fields...
setFields > setFields.log

echo Creating flap wavemaker movement...
cd constant
python flapWaveGen.py
cd ..

echo Running...
olaDyMFoam > olaDyMFoam.log

echo Simulation complete.
