#!/bin/bash

mkdir 0

echo blockMesh meshing...
blockMesh > blockMesh.log

echo Creating floating object...
topoSet > topoSet.log
subsetMesh -overwrite c0 -patch floatingObject > subsetMesh.log

echo Preparing 0 folder...
rm -fr 0
cp -r 0.org 0

echo Setting the fields...
setFields > setFields.log

echo Running...
olaDyMFlow > olaDyMFlow.log

echo Simulation complete.
