#!/bin/bash

ofversion=`echo $WM_PROJECT_VERSION | sed -e 's/\./\n/g' -e 's/-/\n/' | grep "[0-9]" | tr -d '\n'`
export OF_VERSION=$ofversion

wclean all > /dev/null

wmake libso waveGeneration

if (( $? )) ; then 
    echo "\n\nWave generation boundary conditions compilation failed"
    exit; else
    echo -e "\n\nWave generation boundary conditions compiled successfully for OpenFOAM $ofversion\n\n\n";  
fi

wmake libso waveAbsorption

if (( $? )) ; then 
    echo "\n\nWave absorption boundary conditions compilation failed"
    exit; else
    echo -e "\n\nWave absorption boundary conditions compiled successfully for OpenFOAM $ofversion\n\n\n";  
fi

wclean all > /dev/null
