#!/bin/bash

if [ $WM_PROJECT == "foam" ]; then
    # FOAM-Extend
    export OF_VERSION=`echo $WM_PROJECT_VERSION | sed -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -2 | tr -d '\n'`
    export OF_FLAVOUR=1
else
    if [[ $WM_PROJECT_VERSION == *"+"* ]]
    then
        # OpenFOAM +
        export OF_VERSION=`echo $WM_PROJECT_VERSION"-0" | sed -e 's/v//' -e 's/+//' -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -3 | tr -d '\n' | head -c4`
        export OF_FLAVOUR=2
    else
        # OpenFOAM
        export OF_VERSION=`echo $WM_PROJECT_VERSION"-0" | sed -e 's/v//' -e 's/+//' -e 's/\.x/-9/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -3 | tr -d '\n'`
        export OF_FLAVOUR=3
    fi
fi

wclean all > /dev/null

wmake libso waveGeneration

if (( $? )) ; then 
    echo "\n\nWave generation boundary conditions compilation failed"
    exit; else
    echo -e "\n\nWave generation boundary conditions compiled successfully for $WM_PROJECT $WM_PROJECT_VERSION\n\n\n";  
fi

wmake libso waveAbsorption

if (( $? )) ; then 
    echo "\n\nWave absorption boundary conditions compilation failed"
    exit; else
    echo -e "\n\nWave absorption boundary conditions compiled successfully for $WM_PROJECT $WM_PROJECT_VERSION\n\n\n";  
fi

wclean all > /dev/null
rm -f common/waveFun.dep

if [ $WM_PROJECT == "foam" ]; then
    rm -fr */lnInclude
fi
