#!/bin/bash

if [ $WM_PROJECT == "foam" ]; then
    # FOAM-Extend
    export OF_FLAVOUR=1
else
    if [[ $WM_PROJECT_VERSION == *"v"* ]] && [ $WM_PROJECT_VERSION != "dev" ]
    then
        # OpenFOAM +
        export OF_FLAVOUR=2
    else
        # OpenFOAM
        export OF_FLAVOUR=3
    fi
fi

if [ $OF_FLAVOUR -eq 2 ]; then
    cp system/controlDict_OF+ system/controlDict
else
    cp system/controlDict_OF system/controlDict
fi

mkdir 0

cp constant/turbulenceProperties_keps constant/turbulenceProperties

echo blockMesh meshing...
blockMesh > blockMesh.log

echo snappyHexMesh meshing...
snappyHexMesh -overwrite > snappyHexMesh.log

sed -i 's/caisson_diqueMixto/caisson/g' constant/polyMesh/boundary

echo Preparing 0 folder...
rm -fr 0
cp -r 0.org 0

echo Setting the fields...
setFields > setFields.log

echo Running...
olaFlow > olaFlow.log

echo Simulation complete

echo Processing and plotting variables
python postSensVOF.py
python postSensPres.py
python plotSensVOF.py
python plotSensPres.py

